(kill(all),0);
0$

/* bogus arguments */
errcatch(jacobi_p());
[]$

errcatch(jacobi_p(3));
[]$

errcatch(jacobi_p(a,b,c,d,e));
[]$

(op_and_args(e) := block([inflag:true],
    if mapatom(e) then false else [nounify(op(e)), args(e)]),0);
0$

/* basic values */
jacobi_p(0,a,b,x);
1$

jacobi_p(1,a,b,x);
((a+b+2)*x + (a-b))/2$

/* require explicit integer degree */
op_and_args(jacobi_p(1.0,a,b,x));
[jacobi_p, [1.0, a, b, x]]$

/* DLMF Table Table 18.6.1:*/
block([ans],
    declare(n,integer),
    assume(n >= 0),
    ans : jacobi_p(n,a,b,1),
    remove(n,integer),
    forget(n >= 0),
    ans);
pochhammer(a+1,n)/n!$

/* for the jacobi_p(n,a,b,1) simplification, make sure that n is a nonnegative integer. */
op_and_args(jacobi_p(n,3,4,1));
[jacobi_p, [n, 3, 4, 1]]$

block([ans,one],
    declare(n,integer),
    assume(n >= 0),
    one : jacobi_p(n,a,b,1),
    ans : makelist(subst(n=k, one) - subst(x=1, jacobi_p(k,a,b,x)),k,0,6),
    remove(n,integer),
    forget(n >= 0),
    ratsimp(ans));
[0, 0, 0, 0, 0, 0, 0]$

/* Rodrigues formula */
(fn : orthopoly_rodrigues(jacobi_p),0);
0$

makelist(ratsimp(fn(k,a,b,x) - jacobi_p(k,a,b,x)), k,0,10);
[0,0,0,0,0,0,0,0,0,0,0]$

/* gradient */
block([df :  diff(jacobi_p(n,a,b,x),x)],
  ratsimp(makelist(subst(n=k,df) - diff(jacobi_p(k,a,b,x),x),k,0,10)));
[0,0,0,0,0,0,0,0,0,0,0]$


/* orthogonality: A&S 22.2.1 */
block([w,s,Q],
  w : orthopoly_weight('jacobi_p)(x,2,3),
  s : orthopoly_normalization('jacobi_p),
  Q : lambda([n,m], integrate(jacobi_p(n,2,3,x)*jacobi_p(m,2,3,x)*first(w),x,second(w),third(w))
      - kron_delta(n,m)*s(n,2,3)),
  makelist(makelist(Q(n,m),n,0,6),m,0,6));
[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]]$

/* reflection: P_n^{(a,b)}(-x) = (-1)^n P_n^{(b,a)}(x) */
ratsimp(makelist(jacobi_p(n,a,b,-x) - (-1)^n*jacobi_p(n,b,a,x), n,0,10));
[0,0,0,0,0,0,0,0,0,0,0]$

/* explicit low-degree checks */
ratsimp([
 jacobi_p(0,a,b,x) - 1,
 jacobi_p(1,a,b,x) - ((a+b+2)*x + (a-b))/2]);
 [0,0]$

/* numeric tests */
jacobi_p(5,0,0,2.3);
404.71326125$

jacobi_p(5,0,0,23/10);
323770609/800000$

subst(x=23/10, jacobi_p(5,0,0,x));
323770609/800000$

/* rectangular form */
(declare(z,complex),0);
0$

conjugate(jacobi_p(n,a,b,z));
jacobi_p(n,conjugate(a),conjugate(b),conjugate(z))$

(remove(z,complex),0);
0$

/* ODE check */
(fn : orthopoly_ode('jacobi_p),0);
0$

expand(fn(5,a,b,z,jacobi_p(5,a,b,z)));
0$

(remvalue(fn),0);
0$

/* recursion check */
(fn : orthopoly_recursion('jacobi_p),0);
0$

is(fn(2,2,3,4));
true$

is(fn(12,2/3,-1/4,7));
true$

(remvalue(fn),0);
0$

/* nounform return checks */
block([ans : jacobi_p(-1,a,b,x)], [op(ans), args(ans)]);
[jacobi_p, [-1, a, b, x]]$

block([ans : jacobi_p(-1,a,b,42)], [op(ans), args(ans)]);
[jacobi_p, [-1, a, b, 42]]$

/* binary64 tests */
(approx_equal(x,y) := is(abs(x-y) < 5*10^(-15)*max(1,abs(x))),0);
0$

block([N:4, fails : [], maxD:12, x,y],
  for d:maxD-1 thru maxD do (
    for k:-N thru N do (
      for l:-N thru N do (
        x:float(k/N),
        y:float(l/N),
        if not approx_equal(
                 jacobi_p(d,3/2,1/2,rationalize(x+%i*y)),
                 jacobi_p(d,3/2,1/2,x+%i*y)) then 
        push([d,x+%i*y, fails])))),
  fails);
[]$

(fpprec:28,0);
0$

block([N:4, fails : [], maxD:12, x,y],
  for d:maxD-1 thru maxD do (
    for k:-N thru N do (
      for l:-N thru N do (
        x:bfloat(k/N),
        y:bfloat(l/N),
        if not approx_equal(
                 jacobi_p(d,3/2,1/2,rationalize(x+%i*y)),
                 jacobi_p(d,3/2,1/2,x+%i*y)) then 
        push([d,x+%i*y, fails])))),
  fails);
[]$

(reset(fpprec),0);
0$

/* tidy up */
values;
[]$

facts();
[]$

contexts;
[initial,global]$
