(kill(all),0);
0$

(approx_equal(x,y) := is(abs(x-y) < 10^(-15)*max(1,abs(x))),0);
0$

/* bogus arguments */
errcatch(ultraspherical());
[]$

errcatch(ultraspherical(3));
[]$

errcatch(ultraspherical(a,b,c,d));
[]$

(op_and_args(e) := block([inflag:true],  if mapatom(e) then false else [nounify(op(e)), args(e)]),0);
0$

/* basic values */
ultraspherical(0, lam, x);
1$

ultraspherical(1, lam, x);
2*lam*x$

/* require explicit integer for degree */
op_and_args(ultraspherical(1.0, lam, x));
[ultraspherical, [1.0, lam, x]]$

op_and_args(ultraspherical(1.0b0, lam, x));
[ultraspherical, [1.0b0, lam, x]]$


/* value at x = 1; See DLMF  Table 18.6.1*/
block([ans],
    declare(n,integer),
    ans : ultraspherical(n, lam, 1),
    remove(n,integer),
    ans);
pochhammer(2*lam,n)/n!$

makelist(is(ratsimp(subst(x=1, pochhammer(2*lam,k)/k! = ultraspherical(k,lam,x)))),k,0,6);
[true,true,true,true,true,true,true]$

/* Rodrigues formula */
(fn : orthopoly_rodrigues(ultraspherical),0);
0$

makelist(ratsimp(fn(k,lam,x) - ultraspherical(k,lam,x)), k,0,10);
[0,0,0,0,0,0,0,0,0,0,0]$

/* gradient */
(df : diff(ultraspherical(n,lam,x),x),
 expand(makelist(subst(n=k,df) - diff(ultraspherical(k,lam,x),x),k,1,10)));
[0,0,0,0,0,0,0,0,0,0]$

(remvalue(fn,df),0);
0$

/* orthogonality (A&S 22.2.3) */
block([w,s,Q],
  w : orthopoly_weight('ultraspherical)(x,5),
  s : orthopoly_normalization('ultraspherical),
  Q : lambda([n,m], integrate(ultraspherical(n,5,x)*ultraspherical(m,5,x)*first(w),x,second(w),third(w))
      - kron_delta(n,m)*s(n,5)),
  makelist(makelist(Q(n,m),n,0,6),m,0,6));
 [[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0]]$

/* reflection: C_n^lam(-x) = (-1)^n C_n^lam(x) */
ratsimp(makelist(ultraspherical(n,lam,-x) - (-1)^n*ultraspherical(n,lam,x), n,0,10));
[0,0,0,0,0,0,0,0,0,0,0]$

/* explicit low-degree checks */
ratsimp([
  ultraspherical(0,lam,x),
  ultraspherical(1,lam,x),
  ultraspherical(2,lam,x),
  ultraspherical(3,lam,x)
]);
 [1,2*lam*x,(2*lam^2+2*lam)*x^2-lam,((4*lam^3+12*lam^2+8*lam)*x^3+(-(6*lam^2)-6*lam)*x)/3]$

/* numeric tests */
ultraspherical(5, 3/2, 2.3);
4647.51837375$

ultraspherical(5, 3/2, 23/10);
3718014699/800000$

subst(x=23/10, ultraspherical(5,3/2,x));
3718014699/800000$

/* rectangular form */
(declare(z,complex),declare(lam,complex), 0);
0$

conjugate(ultraspherical(n,lam,z));
ultraspherical(n,conjugate(lam),conjugate(z))$

(remove(z,complex),remove(lam,complex), 0);
0$

/* ODE check */
(fn : orthopoly_ode('ultraspherical),0);
0$

expand(fn(5,lam,z,ultraspherical(5,lam,z)));
0$

(remvalue(fn),0);
0$

/* recursion check */
(fn : orthopoly_recursion('ultraspherical),0);
0$

is(expand(fn(5,a,x)));
true$

is(expand(fn(2,a,x)));
true$

is(expand(fn(8,a,x)));
true$

(remvalue(fn),0);
0$

/* nounform return checks */
block([ans : ultraspherical(-1,lam,x)], [op(ans), args(ans)]);
[ultraspherical, [-1, lam, x]]$

block([ans : ultraspherical(-1,lam,42)], [op(ans), args(ans)]);
[ultraspherical, [-1, lam, 42]]$

/* binary64 tests */

block([N:4, okay:true, maxD:12, x,y],
  for d:maxD-1 thru maxD do (
    for k:-N thru N do (
      for l:-N thru N do (
        x:float(k/N),
        y:float(l/N),
        okay:okay and approx_equal(
                 ultraspherical(d,3/2,rationalize(x+%i*y)),
                 ultraspherical(d,3/2,x+%i*y))))),
  okay);
true$

(fpprec:28,0);
0$

block([N:4, okay:true, maxD:12, x,y],
  for d:maxD-1 thru maxD do (
    for k:-N thru N do (
      for l:-N thru N do (
        x:bfloat(k/N),
        y:bfloat(l/N),
        okay:okay and approx_equal(
                 ultraspherical(d,3/2,rationalize(x+%i*y)),
                 ultraspherical(d,3/2,x+%i*y))))),
  okay);
true$

(reset(fpprec),0);
0$

/* high degree float */
approx_equal(ultraspherical(500, 1/2, 1/4+%i) , ultraspherical(500, 1/2, 0.25+%i));
true$

approx_equal(ultraspherical(500, 1/2, 1/4+%i) , ultraspherical(500, 1/2, 0.25b0+%i));
true$

/* tidy up */

(kill(values),0);
0$

values;
[]$

facts();
[]$

contexts;
[initial,global]$
