(kill(all),0);
0$

/* bogus arguments */
errcatch(hermite());
[]$

errcatch(hermite(12));
[]$

errcatch(hermite(a,b,c));
[]$

(op_and_args(e) := block([inflag : true], if mapatom(e) then false else [nounify(op(e)), args(e)]),0);
0$

/* basic values */
hermite(0,x);
1$

hermite(1,x);
2*x$

/* require explicit integer for degree, not a float or bigfloat. */
op_and_args(hermite(1.0,x));
[hermite, [1.0, x]]$

op_and_args(hermite(1.0b0,x));
[hermite, [1.0b0, x]]$

/*nounform for negative degree or noninteger degree*/
op_and_args(hermite(-6,x));
 [hermite, [- 6, x]]$

op_and_args(hermite(2/3,x));
[hermite,[2/3,x]]$

op_and_args(hermite(2<5,x));
[hermite,[2<5,x]]$

/*  Check the value at 0 */
block([ans], declare(n,even), ans : hermite(n,0), remove(n,even), ans);
 (2^n*sqrt(%pi))/gamma((1-n)/2)$

block([ans], 
    declare(n,even), 
    ans : hermite(n,0), 
    remove(n,even),
    makelist(is(subst(n=2*k,ans) = hermite(2*k,0)),k,0,5));
 [true,true,true,true,true,true]$

/* Check the Rodrigues form */
(fn : orthopoly_rodrigues(hermite),0);
0$

makelist(ratsimp(fn(k,x)-hermite(k,x)),k,0,10);
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]$

/* Check the gradient */
(df : diff(hermite(n,x),x), expand(makelist(subst(n=k,df)-diff(hermite(k,x),x),k,0,10)));
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]$

 string(diff(hermite(n*x,x),x));
"'diff(hermite(n*x,x),x,1)"$

string(diff(hermite(n*x,x),n));
"'diff(hermite(n*x,x),n,1)"$

(remvalue(fn,df),0);
0$

/*taylorize */
hermite(n,taylor(x,x,0,2));
hermite(n,0)+2*hermite(n-1,0)*n*x+(2*n^2-2*n)*hermite(n-2,0)*x^2$

ratdisrep(subst(n=8, hermite(n,taylor(x,x,0,2))) - taylor(hermite(8,x),x,0,2));
0$

/* tests adapted from rtest_orthopoly  */
/* See A&S 22.2.14 page 775 */

block([w,s,Q],
  w : orthopoly_weight('hermite)(x),
  s : orthopoly_normalization('hermite),
  Q : lambda([n,m], integrate(hermite(n,x)*hermite(m,x)*first(w),x,second(w),third(w)) - kron_delta(n,m)*s(n)),
  makelist(makelist(Q(n,m),n,0,6),m,0,6));
  [[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0]]$

block([w,Q],
  w : orthopoly_weight('hermite)(x),
  Q : lambda([n,m], integrate(x*hermite(n,x)*hermite(m,x)*first(w),x,second(w),third(w))),
  makelist(makelist(Q(n,m),n,0,6),m,0,6));
  
[[0,sqrt(%pi),0,0,0,0,0],[sqrt(%pi),0,4*sqrt(%pi),0,0,0,0],
        [0,4*sqrt(%pi),0,24*sqrt(%pi),0,0,0],
        [0,0,24*sqrt(%pi),0,192*sqrt(%pi),0,0],
        [0,0,0,192*sqrt(%pi),0,1920*sqrt(%pi),0],
        [0,0,0,0,1920*sqrt(%pi),0,23040*sqrt(%pi)],
        [0,0,0,0,0,23040*sqrt(%pi),0]]$

/* See A&S 22.12.8 page 785*/

block([ans],
  fn(n) := hermite(n,x+y) - sum(binomial(n, k) * hermite(k,sqrt(2)*x) * hermite(n-k,sqrt(2)*y),k,0,n) / 2^(n/2),
  ans : makelist(ratsimp(fn(n)), n, 0, 7),
  remfunction(fn),
  ans);
 [0, 0, 0, 0, 0, 0, 0, 0]$

 /* See G&R 8.950 (1) page 1033 */
 ratsimp(makelist(hermite(n,x) - (-1)^n * exp(x^2) * diff(exp(-x^2),x,n),n,0,9));
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]$

/* See G&R 8.952 (1) page 1033*/
ratsimp(makelist(diff(hermite(n,x),x) - 2 * n * hermite(n-1,x),n,1,7));
[0, 0, 0, 0, 0, 0, 0]$


/* See G&R 8.952 (2) page 1033 */
ratsimp(makelist(hermite(n+1,x) - 2 * x * hermite(n,x) + 2 * n * hermite(n-1,x),n,1,7));
[0, 0, 0, 0, 0, 0, 0]$

/* See G&R 8.956 (1-3) page 1034 */
ratsimp([hermite(0,x) - 1,
         hermite(1,x) - 2*x,
	 hermite(2,x) - (4*x^2 -2),
	 hermite(3,x) - (8*x^3-12*x),
	 hermite(4,x) - (16*x^4 - 48 * x^2 + 12)]);
[0, 0, 0, 0, 0]$

block([ans : [],foo],
   for i : 0 thru 15 do (
      foo : diff(hermite(n,x^2) - hermite(i,x^2),x),
      foo : subst(n=i,foo),
      foo : ratsimp(foo),
      ans  : cons(foo, ans)),
   ans);
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]$

hermite(5,2.3);
388.9097599999996$

hermite(5,23/10);
1215343/3125$

subst(x=23/10, hermite(5,x));
1215343/3125$

/* end tests adapted from rtest_orthopoly */

(declare(z,complex),0);
0$

conjugate(hermite(n,z));
hermite(n, conjugate(z))$

(remove(z,complex),0);
0$

/* reflection */

(declare(n,even),0);
0$

hermite(n,x) - hermite(n,-x);
0$

hermite(n+1,x) + hermite(n+1,-x);
0$

hermite(k,-x) + hermite(k,x);
(-1)^k*hermite(k,x)+hermite(k,x)$

(remove(n,even),0);
0$

/* gradient */
diff(hermite(n,x),x);
2*n*hermite(n-1,x)$

diff(hermite(k,p),p);
2*k*hermite(k-1,p)$

(inflag : true,0);
0$

/* Make sure hermite returns values in rectangular form */
hermite(5, (1 + sqrt(3)*%i/2));
 -(151*sqrt(3)*%i)+202$

hermite(5, 1/(3 + %i));
-((24816*%i-103488)/3125)$

/* --- Orthogonality checks  --- */

([w,a,b] : orthopoly_weight('hermite)(z),0);
0$

integrate(hermite(0,z)*hermite(1, z)*w, z, a,b);
0$

integrate(hermite(2,z)*hermite(3, z)*w, z, a,b);
0$

integrate(hermite(2,z)^2*w, z, a,b);
2^2 * 2! * sqrt(%pi)$

(remvalue(w,a,b),0);
0$

/* antiderivative */
integrate(hermite(n,x),x,0,z);
hermite(n+1,z)/(2*n+2)-hermite(n+1,0)/(2*n+2)$

ratsimp(diff(integrate(hermite(n,x),x,0,z),z));
hermite(n,z)$

/* Nounform return checks */
block([ans : hermite(-1, x)], [op(ans), args(ans)]);
[hermite, [- 1, x]]$

block([ans : hermite(-1, 42)], [op(ans), args(ans)]);
[hermite, [- 1, 42]]$

/* binary64 tests */
(approx_equal(x,y) := is(abs(x-y) < 10^(-15) * max(1,abs(x))),0);
0$

block([N : 4, okay : true, maxD : 32,x,y],
 for d : maxD-1 thru maxD do (
  for k : -N thru N do (
    for l : -N thru N do (
        x : float(k/N),
        y : float(l/N),
        okay : okay and approx_equal(hermite(d, rationalize(x+%i*y)), hermite(d, x+%i*y))))),
    okay);
true$

(fpprec : 28,0);
0$

block([N : 4, okay : true, maxD : 32,x,y],
 for d : maxD-1 thru maxD do (
  for k : -N thru N do (
    for l : -N thru N do (
        x : bfloat(k/N),
        y : bfloat(l/N),
        okay : okay and approx_equal(hermite(d, rationalize(x+%i*y)), hermite(d, x+%i*y))))),
    okay);
true$

(reset(fpprec),0);
0$

block([bad : [],n,x,exact, approx, eps : 10^-14],
     for i : -5000 thru 5000 do (
         n : random(32),
         x : float(i/50),
         exact : hermite(n,rationalize(x)),
         approx : hermite(n,x),
         if abs(exact-approx) > eps * max(1, abs(exact)) then push([n,rationalize(x)], bad)), 
    bad);
[]$

/* see  https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/issues/280 */
block([n : 50, x : -9.182406958129], approx_equal(hermite(n,x), hermite(n, rationalize(x))));
true$

block([n : 5, x : 2.0201828704560856], approx_equal(hermite(n,x), hermite(n, rationalize(x))));
true$

/* ode */
 (fn : orthopoly_ode('hermite),0);
 0$

fn(10, z,hermite(10,z)), expand;
0$

/* recursion */
(fn : orthopoly_recursion('hermite),0);
0$

is(fn(0,z));
true$

 is(fn(1,z));
 true$

is(ratsimp(fn(28,z)));
true$

(remvalue(fn),0);
0$

(remfunction(op_and_args), remfunction(approx_equal),0);
0$

/* Let's check the values in the DLMF table 18.6.1: Classical OP’s: symmetry and special values.
Here I have the tests for all applicable the rows of this table, not just the Hermite polynomial row.*/
(declare(n,integer), assume(n >= 0),0);
0$

[jacobi_p(n,a,b,-x), jacobi_p(n,a,b,1)];
[(-1)^n*jacobi_p(n,b,a,x),pochhammer(a+1,n)/n!]$

[jacobi_p(n,a,a,-x), jacobi_p(n,a,a,1), jacobi_p(2*n,a,a,0),at(diff(jacobi_p(2*n+1,a,a,x),x),x=0)];
[(-1)^n*jacobi_p(n,a,a,x),pochhammer(a+1,n)/n!,
       ((-1)^n*pochhammer(n+a+1,2*n))/(4^n*n!),
       (2*(-1)^n*(2*n+a+1)^2*pochhammer(n+a+1,2*n))/(4^n*(2*(2*n+1)+2*a)*n!)]$

[ultraspherical(n,lam,-x),
        ultraspherical(n,lam,1), 
        ultraspherical(2*n,lam,0),
        at(diff(ultraspherical(2*n+1,lam,x),x),x=0)];
[(-1)^n*ultraspherical(n,lam,x),pochhammer(2*lam,n)/n!,
 ((-1)^n*pochhammer(lam,n))/n!,(2*(-1)^n*lam*pochhammer(lam+1,n))/n!]$

[chebyshev_t(n,-x),
        chebyshev_t(n,1),
        chebyshev_t(2*n,0),
        at(diff(chebyshev_t(2*n+1,x),x),x=0)];
[(-1)^n*chebyshev_t(n,x),1,(-1)^n,(-1)^n*(2*n+1)]$

[chebyshev_u(n,-x),
        chebyshev_u(n,1),
        chebyshev_u(2*n,0),
        at(diff(chebyshev_u(2*n+1,x),x),x=0)];
[(-1)^n*chebyshev_u(n,x),n+1,(-1)^n,(-1)^n*(2*n+2)]$

[legendre_p(n,-x),
        legendre_p(n,1),
        legendre_p(2*n,0),
         at(diff(legendre_p(2*n+1,x),x),x=0)];
[(-1)^n*legendre_p(n,x),1,((-1)^n*pochhammer(1/2,n))/n!,
        ((-1)^n*pochhammer(1/2,n)*(2*n+1))/n!]$

[hermite(n,-x),
        hermite(n,1),
        hermite(2*n,0),
        at(diff(hermite(2*n+1,x),x),x=0)];
[(-1)^n*hermite(n,x),hermite(n,1),(2^(2*n)*sqrt(%pi))/gamma((1-2*n)/2),
        (2^(2*n+1)*sqrt(%pi)*(2*n+1))/gamma((1-2*n)/2)]$

/* Let's keep our environment tidy. */
(forget(n>=0), remove(n,integer),0);
0$

values;
[]$

facts();
[]$

contexts;
[initial,global]$


