/* unit_step */

block([ans : unit_step(x)],
   [op(ans), args(ans)]);
[unit_step, [x]]$

unit_step(-42);
0$

unit_step(0);
0$

unit_step(zerob);
0$

unit_step(zeroa);
1$

unit_step(107);
1$

sign(unit_step(x));
pz$


/* jacobi polynomial edge cases*/
jacobi_p(0, a, b, x);
1$

jacobi_p(1, a, b, x);
((a+b+2)*x+a-b)/2$

jacobi_p(1, a, b, 1);
 (2*a+2)/2$

ratsimp(jacobi_p(2, a, b, 1),x);
(a^2+3*a+2)/2$

/* value at x = 1 */
jacobi_p(n,a,b,1);
pochhammer(a+1,n)/n!$

rectform(subst(x=1, jacobi_p(6,%i,2/3,x)) - pochhammer(%i+1,6)/6!);
0$

/* reflection */

block([ans],
 declare(n,even),
 ans : jacobi_p(n,a,b,x) - jacobi_p(n,b,a,-x),
 remove(n,even),
 ans);
0$

block([ans],
 declare(n,odd),
 ans : jacobi_p(n,a,b,x) + jacobi_p(n,b,a,-x),
 remove(n,odd),
 ans);
0$

/*  Rodrigue's formulae */

(jacobi_p_rodrigue(n,a,b,x) := block([ an, rho, g , t : gensym()],
    an : (-1)^n * 2^n * n!,
    rho : (1-t)^a * (1 + t)^b,
    g : 1-t^2,
    rat(subst(x,t, diff(rho * g^n,t,n) / (an * rho)))),0);
0$

block([n : 0], expand(jacobi_p(n,a,b,x) - jacobi_p_rodrigue(n,a,b,x)));
0$

block([n : 1], expand(jacobi_p(n,a,b,x) - jacobi_p_rodrigue(n,a,b,x)));
0$

block([n : 2], expand(jacobi_p(n,a,b,x) - jacobi_p_rodrigue(n,a,b,x)));
0$

block([n : 9, a : 2/3, b : 1/5], expand(jacobi_p(n,a,b,x) - jacobi_p_rodrigue(n,a,b,x)));
0$

block([n : 9, a : %i, b : 0], expand(jacobi_p(n,a,b,x) - jacobi_p_rodrigue(n,a,b,x)));
0$

block([n : 9, a : 1/2 + %i, b : 1/2 - %i], expand(jacobi_p(n,a,b,x) - jacobi_p_rodrigue(n,a,b,x)));
0$

block([n : 9], expand(jacobi_p(n,a,b,x) - jacobi_p_rodrigue(n,a,b,x)));
0$

/* check jacobi polynomial gradient */

ratsimp(subst(n=2, diff(jacobi_p(n,2/3,1/6,x),x,3)));
0$

ratsimp(subst(n=3, diff(jacobi_p(n,a,b,x),x,4)));
0$

block([ans : jacobi_p(10,2,3,x), dans : jacobi_p(n,2,3,x)],
  dans : diff(dans,x),
  ans : diff(ans,x),
  ratsimp(ans - subst(n=10, dans)));
0$

block([ans : jacobi_p(2,2,3,x), dans : jacobi_p(n,2,3,x)],
  dans : diff(dans,x,2),
  ans : diff(ans,x,2),
  ratsimp(ans - subst(n=2, dans)));
0$

