(kill(all),0);
0$

/* bogus arguments */
errcatch(assoc_legendre_p());
[]$

errcatch(assoc_legendre_p(3));
[]$

errcatch(assoc_legendre_p(a,b,c,d));
[]$

(op_and_args(e) := block([inflag:true],
    if mapatom(e) then false else [nounify(op(e)), args(e)]),0);
0$

/* basic values */
assoc_legendre_p(0,0,x);
1$

assoc_legendre_p(1,0,x);
x$

assoc_legendre_p(1,1,x);
- sqrt(1-x^2)$

/* require explicit integer degrees */
op_and_args(assoc_legendre_p(1.0,0,x));
[assoc_legendre_p, [1.0, 0, x]]$

/* Condon–Shortley phase:
   P_l^{-m}(x) = (-1)^m (l-m)!/(l+m)! P_l^m(x)
*/
ratsimp(makelist(makelist(assoc_legendre_p(l,-m,x)- (-1)^m * factorial(l-m)/factorial(l+m) * assoc_legendre_p(l,m,x),m,0,l),l,0,7));
[[0],[0,0],[0,0,0],[0,0,0,0],[0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0]]$

/* reflection:
   P_l^m(-x) = (-1)^{l+m} P_l^m(x)
*/
ratsimp(makelist(makelist(assoc_legendre_p(l,m,-x) - (-1)^(l+m)*assoc_legendre_p(l,m,x),m,0,l),l,0,7));
[[0], [0, 0], [0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]$

/* Rodrigues formula */
(fn : orthopoly_rodrigues(assoc_legendre_p),0);
0$

ratsimp(makelist(makelist(fn(l,m,x) - assoc_legendre_p(l,m,x), m,0,l),l,0,7));
[[0], [0, 0], [0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]$

(remvalue(fn),0);
0$

/* numeric tests */
assoc_legendre_p(5,2,1.5);
- 566.015625$

assoc_legendre_p(5,2,3/2);
-(36225/64)$

subst(x=3/2, assoc_legendre_p(5,2,x));
-(36225/64)$

/* rectangular form */
(declare(z,complex),0);
0$

conjugate(assoc_legendre_p(l,m,z));
assoc_legendre_p(l,m,conjugate(z))$

(remove(z,complex),0);
0$

/* negative degree */
assoc_legendre_p(-1,0,x);
1$

block([ans : assoc_legendre_p(3,4,x)], [op(ans), args(ans)]);
[assoc_legendre_p, [3, 4, x]]$

/* binary64 tests */
(approx_equal(x,y) := is(abs(x-y) < 10^(-15)*max(1,abs(x))),0);
0$

block([L:4, okay, fails : [], x],
  for l : 0 thru L do (
    for m : -l thru l do (
      for k : -L thru L do (
        x:float(k/L),
        okay : approx_equal(
                 assoc_legendre_p(l,m,rationalize(x)),
                 assoc_legendre_p(l,m,x)),
        if not okay then (
          push([l,m,x], fails))))),
  fails);
[]$

(fpprec:28,0);
0$

block([L:4, okay:true, x],
  for l:0 thru L do (
    for m:-l thru l do (
      for k:-L thru L do (
        x:bfloat(k/L),
        okay:okay and approx_equal(
                 assoc_legendre_p(l,m,rationalize(x)),
                 assoc_legendre_p(l,m,x))))),
  okay);
true$

(reset(fpprec),0);
0$

/* tidy up */
values;
[]$

facts();
[]$

contexts;
[initial,global]$
