(kill(all),0);
0$

/* bogus arguments */
errcatch(spherical_hankel1());
[]$

errcatch(spherical_hankel1(3));
[]$

errcatch(spherical_hankel1(a,b,c));
[]$

(op_and_args(e) := block([inflag:true],
    if mapatom(e) then false else [nounify(op(e)), args(e)]),0);
0$

/* basic values */
spherical_hankel1(0,x);
-((%e^(%i*x)*%i)/x)$

spherical_hankel1(1,x);
-((%e^(%i*x)*x+%e^(%i*x)*%i)/x^2)$

/* require explicit integer degree */
op_and_args(spherical_hankel1(1.0,x));
[spherical_hankel1, [1.0, x]]$

/* reflection: */
spherical_hankel1(n,-x) - (-1)^n*spherical_hankel2(n,x);
0$

/* derivative identity:
   h_n'(x) = h_{n-1}(x) - (n+1)/x * h_n(x)
*/
ratsimp(makelist(
    diff(spherical_hankel1(n,x),x)
      - (spherical_hankel1(n-1,x)
         - (n+1)/x * spherical_hankel1(n,x)),
    n,1,8));
[0,0,0,0,0,0,0,0]$

/* recurrence:
   h_{n+1}(x) = (2n+1)/x * h_n(x) - h_{n-1}(x)
*/
ratsimp(makelist(
    spherical_hankel1(n+1,x)
      - ((2*n+1)/x)*spherical_hankel1(n,x)
      + spherical_hankel1(n-1,x),
    n,1,8));
[0,0,0,0,0,0,0,0]$

/* differential equation:
   x^2 y'' + 2x y' + (x^2 - n(n+1)) y = 0
*/
ratsimp(makelist(
    x^2*diff(spherical_hankel1(n,x),x,2)
      + 2*x*diff(spherical_hankel1(n,x),x)
      + (x^2 - n*(n+1))*spherical_hankel1(n,x),
    n,0,8));
[0,0,0,0,0,0,0,0,0]$

0;
0$
/* numeric tests */
spherical_hankel1(5,2.3);
0.005037487741787818-8.694824790197426*%i$

expand(spherical_hankel1(5,23/10));
(857038500*%e^((23*%i)/10)*%i)/148035889-(41753410*%e^((23*%i)/10))/6436343$

expand(subst(x=23/10,spherical_hankel1(5,x)));
(857038500*%e^((23*%i)/10)*%i)/148035889-(41753410*%e^((23*%i)/10))/6436343$

/* rectangular form */
(declare(z,complex),0);
0$

conjugate(spherical_hankel1(n,z));
spherical_hankel1(n,conjugate(z))$

(remove(z,complex),0);
0$

/* binary64 tests */
(approx_equal(x,y) := is(abs(x-y) < 5*10^(-15)*max(1,abs(x))),0);
0$

block([N:4, okay, fails : [], maxD:12, x,y],
  for d:maxD-1 thru maxD do (
    for k:1 thru N do (
      for l:1 thru N do (
        x:float(k/N),
        y:float(l/N),
        okay : approx_equal(
                 spherical_hankel1(d,rationalize(x+%i*y)),
                 spherical_hankel1(d,x+%i*y)),
        if not okay then push([d,x+%i*y], fails)))),
  fails);
[]$

(fpprec:28,0);
0$

block([N:4, okay, fails : [], maxD:12, x,y],
  for d:maxD-1 thru maxD do (
    for k:1 thru N do (
      for l:1 thru N do (
        x:bfloat(k/N),
        y:bfloat(l/N),
        okay : approx_equal(
                 spherical_hankel1(d,rationalize(x+%i*y)),
                 spherical_hankel1(d,x+%i*y)),
        if not okay then push([d,x+%i*y], fails)))),
  fails);
[]$

(reset(fpprec),0);
0$

/* tidy up */
values;
[]$

facts();
[]$

contexts;
[initial,global]$
