(kill(all),0);
0$

/* bogus arguments */
errcatch(spherical_hankel2());
[]$

errcatch(spherical_hankel2(3));
[]$

errcatch(spherical_hankel2(a,b,c));
[]$

(op_and_args(e) := block([inflag:true],
    if mapatom(e) then false else [nounify(op(e)), args(e)]),0);
0$

/* basic values */
spherical_hankel2(0,x);
(%e^-(%i*x)*%i)/x$

spherical_hankel2(1,x);
-((%e^-(%i*x)*(x-%i))/x^2)$

/* require explicit integer degree */
op_and_args(spherical_hankel2(1.0,x));
[spherical_hankel2, [1.0, x]]$

/* gradient check */
block([df : diff(spherical_hankel2(n,x),x)], ratsimp((subst(n=8, df) - diff(spherical_hankel2(8,x),x))));
0$

/* differential equation:
   x^2 y'' + 2x y' + (x^2 - n(n+1)) y = 0
*/
ratsimp(makelist(
    x^2*diff(spherical_hankel2(n,x),x,2)
      + 2*x*diff(spherical_hankel2(n,x),x)
      + (x^2 - n*(n+1))*spherical_hankel2(n,x),
    n,0,8));
[0,0,0,0,0,0,0,0,0]$

/* explicit low-degree checks */
[spherical_hankel2(0,x), spherical_hankel2(1,x), spherical_hankel2(2,x)];
[(%e^-(%i*x)*%i)/x,-((%e^-(%i*x)*(x-%i))/x^2), -((%e^-(%i*x)*(%i*x^2+3*x-3*%i))/x^3)]$

/* numeric tests */
spherical_hankel2(5,2.3);
8.69482479019743*%i + 0.005037487741786797$

spherical_hankel2(5,23/10);
 -((%e^-((23*%i)/10)*(857038500*%i+960328430))/148035889)$

subst(x=23/10,spherical_hankel2(5,x));
-((1000000*%e^-((23*%i)/10)*((1714077*%i)/2000+96032843/100000))/148035889)$

/* rectangular form */
(declare(z,complex),0);
0$

conjugate(spherical_hankel2(n,z));
spherical_hankel2(n,conjugate(z))$

(remove(z,complex),0);
0$

/* negative degree tests  */
spherical_hankel2(-1,x);
%e^-(%i*x)/x$

/* binary64 tests */
(approx_equal(x,y) := is(abs(x-y) < 10^(-14)*max(10^(-14),abs(x))),0);
0$

block([N:4, fails : [], maxD:5, x,y],
  for d:maxD-1 thru maxD do (
    for k:-N thru N do (
      for l:-N thru N do (
        x:float((k+1/2)/N),
        y:float((l+1/2)/N),
        if not approx_equal(
                 spherical_hankel2(d,rationalize(x+%i*y)),
                 spherical_hankel2(d,x+%i*y))
        then (
          push(x+%i*y, fails))))),
  fails);
[]$

(fpprec:28,0);
0$

block([N:4, fails : [], maxD:5, x,y],
  for d:maxD-1 thru maxD do (
    for k:-N thru N do (
      for l:-N thru N do (
        x:bfloat((k+1/2)/N),
        y:bfloat((l+1/2)/N),
        if not approx_equal(
                 spherical_hankel2(d,rationalize(x+%i*y)),
                 spherical_hankel2(d,x+%i*y))
        then (
          push(x+%i*y, fails))))),
  fails);
[]$

(reset(fpprec),0);
0$

/* tidy up */
values;
[]$

facts();
[]$

contexts;
[initial,global]$
