(kill(all),0);
0$

/* bogus arguments */
errcatch(spherical_harmonic());
[]$

errcatch(spherical_harmonic(2));
[]$

errcatch(spherical_harmonic(a,b,c,d,e));
[]$

(op_and_args(e) := block([inflag:true],
    if mapatom(e) then false else [nounify(op(e)), args(e)]),0);
0$

/* basic values */
spherical_harmonic(0,0,theta,phi);
1/sqrt(4*%pi)$

spherical_harmonic(1,0,theta,phi);
sqrt(3/(4*%pi))*cos(theta)$

spherical_harmonic(1,1,theta,phi);
- sqrt(3/(8*%pi))*sin(theta)*exp(%i*phi)$

/* require explicit integer degrees */
op_and_args(spherical_harmonic(1.0,0,theta,phi));
[spherical_harmonic, [1.0, 0, theta, phi]]$

/* conjugation identity: see http://dlmf.nist.gov/14.30.E6
Y_{l,-m}(θ,φ) = (-1)^m conjugate(Y_{l,m}(θ,φ)
*/
block([fn : lambda([l,m], 
  trigreduce(radcan(spherical_harmonic(l,-m,theta,phi) - (-1)^m * conjugate(spherical_harmonic(l,m,theta,phi)))))],
  makelist(makelist(fn(l,m),m,-l,l),l,0,6));
[[0], [0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]$

/* reflection identity:
   Y_l^m(π-θ, φ+π) = (-1)^l Y_l^m(θ,φ)
*/
block([fn : lambda([l,m],
   spherical_harmonic(l,m, %pi-theta, %pi+phi) - (-1)^l * spherical_harmonic(l,m,theta,phi))],
   makelist(makelist(fn(a,b),b,-a,a),a,0,5));
[[0], [0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]$

/* normalization: ∫ |Y_l^m|^2 dΩ = 1*/

block([fn : lambda([l,m,lp,mp],
       block([w :  orthopoly_weight(spherical_harmonic)(theta,phi)],
     radcan(integrate(integrate(sin(theta) * spherical_harmonic(l,m,theta,phi) * spherical_harmonic(lp,mp,theta,phi),
     theta,0,%pi),phi,0,2*%pi))))],
   [fn(3,2,5,1), fn(1,0,5,-1)]);
[0,0]$
/* explicit low-degree checks */
ratsimp([
 spherical_harmonic(0,0,theta,phi) - 1/sqrt(4*%pi),
 spherical_harmonic(1,0,theta,phi) - sqrt(3/(4*%pi))*cos(theta),
 spherical_harmonic(1,1,theta,phi) + sqrt(3/(8*%pi))*sin(theta)*exp(%i*phi)
]);
[0,0,0]$

/* numeric tests */
spherical_harmonic(3,2,1.2,0.7);
0.31701879374068104*%i + 0.05467836357153942$

spherical_harmonic(3,2,6/5,7/10);
(15*sqrt(7)*%e^((7*%i)/5)*cos(6/5)*sin(6/5)^2)/(4*sqrt(30)*sqrt(%pi))$

subst([theta=6/5,phi=7/10], spherical_harmonic(3,2,theta,phi));
(15*sqrt(7)*%e^((7*%i)/5)*cos(6/5)*sin(6/5)^2)/(4*sqrt(30)*sqrt(%pi))$

/* rectangular form */
(declare(z,complex),0);
0$

block([ans : conjugate(spherical_harmonic(l,m,z,phi))],
[op(ans), args(ans)]);
[conjugate, [spherical_harmonic(l, m, z, phi)]]$

(remove(z,complex),0);
0$

/* nounform return checks */
block([ans : spherical_harmonic(-1,0,theta,phi)], [op(ans), args(ans)]);
[spherical_harmonic, [-1, 0, theta, phi]]$

block([ans : spherical_harmonic(2,3,theta,phi)], [op(ans), args(ans)]);
[spherical_harmonic, [2, 3, theta, phi]]$

/* binary64 tests */
(approx_equal(x,y) := is(abs(x-y) < 10^(-15)*max(1,abs(x))),0);
0$

block([L:4, okay:true, theta,phi],
  for l:0 thru L do (
    for m:-l thru l do (
      for k:-L thru L do (
        for j:-L thru L do (
          theta:float(k/L),
          phi:float(j/L),
          okay:okay and approx_equal(
                   spherical_harmonic(l,m,rationalize(theta),rationalize(phi)),
                   spherical_harmonic(l,m,theta,phi)))))),
  okay);
true$

(fpprec:28,0);
0$

block([L:4, N : 10, fails : [], theta, phi],
  for l : 0 thru L do (
    for m:-l thru l do (
      for k : 0 thru N do (
        for j : -N  thru N  do (
          theta : bfloat(2*%pi * k/ N),
          phi : bfloat(%pi * j /N),
          if not errcatch(approx_equal(
                   spherical_harmonic(l,m,rationalize(theta),rationalize(phi)),
                   spherical_harmonic(l,m,theta,phi))) then push([l,m,theta,phi], fails))))),
  fails);
[]$


(reset(fpprec),0);
0$

/* tidy up */
values;
[]$

facts();
[]$

contexts;
[initial,global]$
